[package]
name = "appflowy-worker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
path = "src/main.rs"
name = "appflowy_worker"

[lib]
path = "src/lib.rs"

[dependencies]
collab.workspace = true
collab-entity.workspace = true
collab-importer.workspace = true
collab-folder.workspace = true
collab-database.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
database.workspace = true
database-entity.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "net"] }
tokio-stream = { version = "0.1", features = ["net"] }
redis = { workspace = true, features = ["aio", "tokio-comp", "connection-manager", "streams"] }
dotenvy = "0.15.0"
axum = "0.7.4"
thiserror = "1.0.58"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
serde_repr = "0.1.18"
futures = "0.3.30"
infra.workspace = true
sqlx = { workspace = true, default-features = false, features = ["runtime-tokio-rustls", "macros", "postgres", "uuid", "chrono", "migrate"] }
secrecy = { version = "0.8", features = ["serde"] }
aws-sdk-s3 = { version = "1.36.0", features = [
  "behavior-version-latest",
  "rt-tokio",
] }
aws-config = { version = "1.5.1", features = ["behavior-version-latest"] }
tokio-util = { version = "0.7.12", features = ["compat"] }
async_zip = { version = "0.0.17", features = ["full"] }
mime_guess = "2.0"
bytes.workspace = true
uuid.workspace = true
mailer.workspace = true
md5.workspace = true
base64.workspace = true
prometheus-client = "0.22.3"
reqwest = "0.12.5"

