[package]
name = "appflowy-indexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "appflowy_indexer"
path = "src/main.rs"

[dependencies]
collab.workspace = true
collab-entity.workspace = true
collab-stream.workspace = true
collab-document.workspace = true
collab-folder.workspace = true
database.workspace = true
database-entity.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
yrs.workspace = true
openai_dive = { workspace = true, features = ["rustls-tls"] }
sqlx = { workspace = true, default-features = false, features = ["runtime-tokio-rustls", "macros", "postgres", "uuid", "chrono"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "net", "sync"] }
tokio-util = { version = "0.7" }
tokio-stream = { version = "0.1", features = ["net"] }
redis = { workspace = true, features = ["aio", "tokio-comp", "connection-manager"] }
futures = "0.3"
log = "0.4"
axum = "0.7"
thiserror = "1.0"
clap = { version = "4.5", features = ["derive", "env"] }
tracing-subscriber = { version = "0.3", features = ["tracing-log", "env-filter", "json"] }
humantime = "2.1"
dashmap = "5.5"
uuid = { version = "1.8", features = ["v4"] }
env_logger = "0.11.3"
async-stream = "0.3"
async-trait = "0.1"
rand = "0.8.5"
dotenvy = "0.15.0"

[dev-dependencies]
env_logger = "0.11"
workspace-template.workspace = true
pgvector = { workspace = true, features = ["sqlx"] }