[package]
name = "appflowy-history"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "appflowy_history"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[dependencies]
collab.workspace = true
collab-entity.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "net"] }
tokio-stream = { version = "0.1", features = ["net"] }
redis = { workspace = true, features = ["aio", "tokio-comp", "connection-manager"] }
dotenvy = "0.15.0"
axum = "0.7.4"
thiserror = "1.0.58"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tower-service = "0.3"
tower-http = { version = "0.5", features = ["cors", "fs"] }
tower = "0.4"
serde_repr = "0.1.18"
collab-stream.workspace = true
chrono = "0.4.37"
uuid = { version = "1.6.1", features = ["v4"] }
sqlx = { workspace = true, default-features = false, features = ["runtime-tokio-rustls", "macros", "postgres", "uuid", "chrono", "migrate"] }
dashmap = "5.5.3"
infra.workspace = true
database.workspace = true
parking_lot = "0.12.1"
bincode.workspace = true
tonic.workspace = true
tonic-proto.workspace = true
futures = "0.3.30"
log = "0.4.20"
prost = "0.12.3"

[dev-dependencies]
assert-json-diff = "2.0.2"
rand = "0.8.5"
serial_test = "3.0.0"
