name: Server

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ main ]

env:
  APP__GOTRUE__BASE_URL: http://localhost:3000
  APP__GOTRUE__JWT_SECRET: hello123
  GOTRUE_SMTP_PASS: ${{ secrets.GOTRUE_SMTP_PASS }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            AppFlowy-Cloud

      - name: Run Docker-Compose
        run: |
          docker-compose up -d

      - name: Add registered user
        run: |
          export GOTRUE_MAILER_AUTOCONFIRM=true
          docker-compose up -d
          curl localhost:9998/signup \
            --data-raw '{"email":"xigahi8979@tipent.com","password":"Hello123!"}' \
            --header 'Content-Type: application/json'
          export GOTRUE_MAILER_AUTOCONFIRM=false
          docker-compose up -d
